export const mockData = [
    {
        name: 'France',
        topLevelDomain: ['.fr'],
        alpha2Code: 'FR',
        alpha3Code: 'FRA',
        callingCodes: ['33'],
        capital: 'Paris',
        altSpellings: ['FR', 'French Republic', 'République française'],
        region: 'Europe',
        subregion: 'Western Europe',
        population: 66186000,
        latlng: [46, 2],
        demonym: 'French',
        area: 640679,
        gini: 32.7,
        timezones: [
            'UTC-10:00',
            'UTC-09:30',
            'UTC-09:00',
            'UTC-08:00',
            'UTC-04:00',
            'UTC-03:00',
            'UTC+01:00',
            'UTC+03:00',
            'UTC+04:00',
            'UTC+05:00',
            'UTC+11:00',
            'UTC+12:00',
        ],
        borders: ['AND', 'BEL', 'DEU', 'ITA', 'LUX', 'MCO', 'ESP', 'CHE'],
        nativeName: 'France',
        numericCode: '250',
        currencies: ['EUR'],
        languages: ['fr'],
        translations: {
            de: 'Frankreich',
            es: 'Francia',
            fr: 'France',
            ja: 'フランス',
            it: 'Francia',
        },
        relevance: '2.5',
    },
    {
        name: 'French Guiana',
        topLevelDomain: ['.gf'],
        alpha2Code: 'GF',
        alpha3Code: 'GUF',
        callingCodes: ['594'],
        capital: 'Cayenne',
        altSpellings: ['GF', 'Guiana', 'Guyane'],
        region: 'Americas',
        subregion: 'South America',
        population: 239648,
        latlng: [4, -53],
        demonym: '',
        area: null,
        gini: null,
        timezones: ['UTC-03:00'],
        borders: ['BRA', 'SUR'],
        nativeName: 'Guyane française',
        numericCode: '254',
        currencies: ['EUR'],
        languages: ['fr'],
        translations: {
            de: 'Französisch Guyana',
            es: 'Guayana Francesa',
            fr: 'Guayane',
            ja: 'フランス領ギアナ',
            it: 'Guyana francese',
        },
        relevance: '0',
    },
];
